// <auto-generated />
using AudioPlayerProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AudioPlayerProject.Migrations.Music
{
    [DbContext(typeof(MusicContext))]
    partial class MusicContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("AudioPlayerProject.Models.Music.Music", b =>
                {
                    b.Property<string>("MusicTitle")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MusicPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusicTitle");

                    b.ToTable("Music");
                });
#pragma warning restore 612, 618
        }
    }
}
